name = "website"
compatibility_date = "2025-08-30"
compatibility_flags = ["nodejs_compat"]

main = "./dist/_worker.js/index.js"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

[vars]
NODE_VERSION = "22.16.0"
