name = "website"
compatibility_date = "2025-08-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

main = "./dist/_worker.js/index.js"

workers_dev = false

[[routes]]
custom_domain = true
pattern = "ghostdev.xyz"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

[vars]
NODE_VERSION = "22.16.0"
